swagger: "2.0"
info:
  description: "This api refers to Bradesco's test"
  version: "1.0.0"
  title: "Consulta endereco API"
  termsOfService: "tbd"
  contact:
    email: "carlos.swamy@gmail.com"
host: "teste"
basePath: "/v1"
tags:
- name: "Consultas"
  description: "Operacoes de consulta"
#  externalDocs:
#    description: "Find out more about our store"
#    url: "http://swagger.io"
schemes:
- "https"
- "http"

paths:

  /v1/consulta/CEP:
    post:
      tags:
      - "Consultas"
      summary: "Retorna endereco pelo CEP"
      description: "Retorna endereco pelo CEP. Fornecer o cep em formato numerico apenas (Ex. 52051280)"
      operationId: "consultarEndereco"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "cep"
        description: "cep"
        required: true
        schema:
          $ref: "#/definitions/ConsultaCepRequestDTO"
      responses:
        200:
          description: "Endereço Localizado"
          schema:
            $ref: "#/definitions/EnderecoResponseDTO"
    
definitions:

  EnderecoResponseDTO:
    type: "object"
    description: "Data transfer object para endereco."
    properties:
      cep:
        type: "string"
      rua:
        type: "string"
      complemento:
        type: "string"
      bairro:
        type: "string"
      cidade:
        type: "string"
      estado:
        type: "string"
      preco:
        type: "number"
        format: "double"

  ConsultaCepRequestDTO:
    type: "object"
    description: "Data transfer object para cep."
    properties: 
      cep:
        type: "string"
    required:
      - cep
  